#!/bin/bash

src='/Development/Production/cpyfldnesting/lab/src'
dest='/Development/Production/cpyfldnesting/lab/dest'
deep=0

function getDirectoryFolders {
    #1 path of folder
    if [ -d "$(echo $1 | sed 's/<BLK>/ /g')" ]; then
        ls -F "$(echo $1 | sed 's/<BLK>/ /g')" | sed '/\/$/!d' | sed 's/ /<BLK>/g'
    fi
}

function processDirectory {
    #1 path of folder
    #2 path of subfolder
    [ "$1" ] || return

    local path=$(echo "$2" | sed 's/\/\/$/\//') #<< secure "is a dir"

    #echo "--${1}/$path" 
       
    for folder in $(getDirectoryFolders "${1}/$path"); do

        echo "deep: $deep acting on: $folder"
		mkdir -p "$(echo "$dest/${path}$folder" | sed 's/<BLK>/ /g')"
		
		let deep=deep+1
		processDirectory "$1" "${path}$folder"
		let deep=deep-1

    done    
}

processDirectory $src
